;;; -*- Gerbil -*-
;;; @generated by POO Flow Sources Lock Feature; DO NOT EDIT.
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;;
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

;;; Included by sources.ss after the public Feature prototypes.

(def Nasa7150_2DSourcesLock
  (sources-lock-value
      "lambda-aitia/nasa-npr-7150.2d/sources"
      "2022-03-08"
      "sha256:286dbc723fbad0e596ad07593d95ce56f7bbdf6526d30719ab3bebd29bc772bb"
      (list
       (.o (:: @ SourceLockEntry.)
           identity: "nasa/npr-7150.2d/appendix-c"
           path: "modules/sdlc/standards/sources/appendix-c.html"
           canonical-uri: "https://nodis3.gsfc.nasa.gov/displayDir.cfm?Internal_ID=N_PR_7150_002D_&page_name=AppendixC"
           exact-version: "2022-03-08"
           representation: 'html
           digest: "sha256:43db1ee92db397ab03d7e1446641154c9cbcc3c47505c33acb1c1f4ba2c81570"
           size-bytes: 71241
           metadata: '((section . appendix-c))
           )
       (.o (:: @ SourceLockEntry.)
           identity: "nasa/npr-7150.2d/chapter2"
           path: "modules/sdlc/standards/sources/chapter2.html"
           canonical-uri: "https://nodis3.gsfc.nasa.gov/displayDir.cfm?Internal_ID=N_PR_7150_002D_&page_name=Chapter2"
           exact-version: "2022-03-08"
           representation: 'html
           digest: "sha256:da495cf1642bfbfff8b9b169b25d6e79f3a2c24009644dff2f9d37ca2f36ddfe"
           size-bytes: 32418
           metadata: '((section . chapter-2))
           )
       (.o (:: @ SourceLockEntry.)
           identity: "nasa/npr-7150.2d/chapter3"
           path: "modules/sdlc/standards/sources/chapter3.html"
           canonical-uri: "https://nodis3.gsfc.nasa.gov/displayDir.cfm?Internal_ID=N_PR_7150_002D_&page_name=Chapter3"
           exact-version: "2022-03-08"
           representation: 'html
           digest: "sha256:3c7c43b491246e70ed626a8f5790ec2fc8dd00906be5da0a89009daa7ebcc896"
           size-bytes: 41047
           metadata: '((section . chapter-3))
           )
       (.o (:: @ SourceLockEntry.)
           identity: "nasa/npr-7150.2d/chapter4"
           path: "modules/sdlc/standards/sources/chapter4.html"
           canonical-uri: "https://nodis3.gsfc.nasa.gov/displayDir.cfm?Internal_ID=N_PR_7150_002D_&page_name=Chapter4"
           exact-version: "2022-03-08"
           representation: 'html
           digest: "sha256:e6abc0f4df29a3b23d5c1a72be578654efd9f2d01aa4e79f3deb0a23970fa9ee"
           size-bytes: 24637
           metadata: '((section . chapter-4))
           )
       (.o (:: @ SourceLockEntry.)
           identity: "nasa/npr-7150.2d/chapter5"
           path: "modules/sdlc/standards/sources/chapter5.html"
           canonical-uri: "https://nodis3.gsfc.nasa.gov/displayDir.cfm?Internal_ID=N_PR_7150_002D_&page_name=Chapter5"
           exact-version: "2022-03-08"
           representation: 'html
           digest: "sha256:45fbb7e92669103f91cad92624cd1322629cbdfb42b2d5290cd35c7974f8f919"
           size-bytes: 18250
           metadata: '((section . chapter-5))
           )
       (.o (:: @ SourceLockEntry.)
           identity: "nasa/npr-7150.2d/chapter6"
           path: "modules/sdlc/standards/sources/chapter6.html"
           canonical-uri: "https://nodis3.gsfc.nasa.gov/displayDir.cfm?Internal_ID=N_PR_7150_002D_&page_name=Chapter6"
           exact-version: "2022-03-08"
           representation: 'html
           digest: "sha256:0aa4d4e7b90b910f3a3d34e5c0443a1ff13828a148ed322cee7c05ad565fbde0"
           size-bytes: 9917
           metadata: '((section . chapter-6))
           ))
      '((authority . nasa-nodis) (standard . "NPR 7150.2D") (effective . "2022-03-08"))))
