;;; -*- Gerbil -*-
;;; @generated by POO Flow Sources Lock Feature; DO NOT EDIT.
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;;
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

;;; Included by sources.ss after the public Feature prototypes.

(def Nasa7150_2DSourcesLock
  (.o (:: @ SourcesLock.)
      lock-id: "lambda-aitia/nasa-npr-7150.2d/sources"
      revision: "2022-03-08"
      digest: "sha256:ce1f9cc53e6969ac93d0104e65f7c1fb8b58492c0a16cba3c7843ade0d702284"
      entries:
      (list
       (.o (:: @ SourceLockEntry.)
           identity: "nasa/npr-7150.2d/chapter2"
           path: "modules/sdlc/standards/sources/chapter2.html"
           canonical-uri: "https://nodis3.gsfc.nasa.gov/displayDir.cfm?Internal_ID=N_PR_7150_002D_&page_name=Chapter2"
           exact-version: "2022-03-08"
           representation: 'html
           digest: "sha256:3ac3318f35fd258cfa0086bb688ae2c71ca53cb0625410b7798de5ef2e02f905"
           size-bytes: 32607
           metadata: '((section . chapter-2))
           )
       (.o (:: @ SourceLockEntry.)
           identity: "nasa/npr-7150.2d/chapter3"
           path: "modules/sdlc/standards/sources/chapter3.html"
           canonical-uri: "https://nodis3.gsfc.nasa.gov/displayDir.cfm?Internal_ID=N_PR_7150_002D_&page_name=Chapter3"
           exact-version: "2022-03-08"
           representation: 'html
           digest: "sha256:227b09e6b37d96f16584b7be94722b4faaacf03fb325a789150cc0b774649cd3"
           size-bytes: 41236
           metadata: '((section . chapter-3))
           )
       (.o (:: @ SourceLockEntry.)
           identity: "nasa/npr-7150.2d/chapter4"
           path: "modules/sdlc/standards/sources/chapter4.html"
           canonical-uri: "https://nodis3.gsfc.nasa.gov/displayDir.cfm?Internal_ID=N_PR_7150_002D_&page_name=Chapter4"
           exact-version: "2022-03-08"
           representation: 'html
           digest: "sha256:c4a00b96984aec132e1618bf3bb08fcecb1fc2ecbef4e4a1eef3bb52d28a280e"
           size-bytes: 24826
           metadata: '((section . chapter-4))
           )
       (.o (:: @ SourceLockEntry.)
           identity: "nasa/npr-7150.2d/chapter5"
           path: "modules/sdlc/standards/sources/chapter5.html"
           canonical-uri: "https://nodis3.gsfc.nasa.gov/displayDir.cfm?Internal_ID=N_PR_7150_002D_&page_name=Chapter5"
           exact-version: "2022-03-08"
           representation: 'html
           digest: "sha256:624ef44a5a748f31078309e4d518d1d446b5ca7e5268d576f0768c2b74b19d60"
           size-bytes: 18439
           metadata: '((section . chapter-5))
           )
       (.o (:: @ SourceLockEntry.)
           identity: "nasa/npr-7150.2d/chapter6"
           path: "modules/sdlc/standards/sources/chapter6.html"
           canonical-uri: "https://nodis3.gsfc.nasa.gov/displayDir.cfm?Internal_ID=N_PR_7150_002D_&page_name=Chapter6"
           exact-version: "2022-03-08"
           representation: 'html
           digest: "sha256:bf0b7df106ed23ec83bc5a0f3d5ea738ca89e48d81078472ba23a1b6b39ac9c2"
           size-bytes: 10106
           metadata: '((section . chapter-6))
           )
       (.o (:: @ SourceLockEntry.)
           identity: "nasa/npr-7150.2d/appendix-c"
           path: "modules/sdlc/standards/sources/appendix-c.html"
           canonical-uri: "https://nodis3.gsfc.nasa.gov/displayDir.cfm?Internal_ID=N_PR_7150_002D_&page_name=AppendixC"
           exact-version: "2022-03-08"
           representation: 'html
           digest: "sha256:7851059bef3c6da3c5369716dde86cc20b92b541325b6340f3714bd93ee14ddc"
           size-bytes: 71430
           metadata: '((section . appendix-c))
           ))
      metadata: '((authority . nasa-nodis) (standard . "NPR 7150.2D") (effective . "2022-03-08"))))
